// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyfSYNKLRkqvSMHp7UAII3nOIECmfW0Pc',
    appId: '1:1073823976455:web:21a9889ca5c835de35aea2',
    messagingSenderId: '1073823976455',
    projectId: 'app-mussic',
    authDomain: 'app-mussic.firebaseapp.com',
    storageBucket: 'app-mussic.firebasestorage.app',
    measurementId: 'G-T0LCZ150ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVduohvBBpdb0I1qujyzJeRJYFKKCdLGg',
    appId: '1:1073823976455:android:d841824b3540cace35aea2',
    messagingSenderId: '1073823976455',
    projectId: 'app-mussic',
    storageBucket: 'app-mussic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVidXOPNSDMDecbWy-hlIlgBcU7PdcwIk',
    appId: '1:1073823976455:ios:0b857e8694bdfb5c35aea2',
    messagingSenderId: '1073823976455',
    projectId: 'app-mussic',
    storageBucket: 'app-mussic.firebasestorage.app',
    iosBundleId: 'com.example.melody',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVidXOPNSDMDecbWy-hlIlgBcU7PdcwIk',
    appId: '1:1073823976455:ios:0b857e8694bdfb5c35aea2',
    messagingSenderId: '1073823976455',
    projectId: 'app-mussic',
    storageBucket: 'app-mussic.firebasestorage.app',
    iosBundleId: 'com.example.melody',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyfSYNKLRkqvSMHp7UAII3nOIECmfW0Pc',
    appId: '1:1073823976455:web:891f7e135ef88fb535aea2',
    messagingSenderId: '1073823976455',
    projectId: 'app-mussic',
    authDomain: 'app-mussic.firebaseapp.com',
    storageBucket: 'app-mussic.firebasestorage.app',
    measurementId: 'G-373D0D11PY',
  );
}
