services:
  redis:
    image: redis:alpine
    container_name: app_music_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mysql:
    image: mysql:8.0
    container_name: app_music_db
    environment:
      MYSQL_DATABASE: app_music
      MYSQL_USER: appmusic
      MYSQL_PASSWORD: appmusic123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: app_music_backend
    environment:
      DB_HOST: mysql
      DB_USER: appmusic
      DB_PASSWORD: appmusic123
      DB_NAME: app_music
      NODE_ENV: development
      ITUNES_API: "https://itunes.apple.com/vn/rss/topsongs/limit=100/json"
      ENABLE_CRON_SYNC: "true"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mysql_data:
  redis_data:
